version: '3'

services:
  idsweb:
    image: idsweb:1.0-beta1
    container_name: idsweb
    build:
      context: ./QuickstartIdentityServer
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_URLS=http://*:80
      - Ids4_Authority=http://192.168.103.251:6006/
      - ASPNETCORE_ENVIRONMENT=Production
      - apollo:AppId=ids
      - apollo:Env=DEV
      - apollo:LocalIp=172.16.0.148
      - apollo:MetaServer=http://192.168.1.115:9080
    ports:
      - "8888:80"